### ISSUE TITLE
Very Slow

### ISSUE THREAD

**Issue by bscully27** [paulbrodersen/entropy-based-binning#1]
Very slow, painfully so.
Any optimization plans?

**Comment by paulbrodersen** [comment]
What are you trying to do?

**Comment by bscully27** [comment]
Bin a 200 element 1d array.  Never let the code run to completion bc it
took over 10 seconds with something that should be done immediately.

**Comment by paulbrodersen** [comment]
That seems strange. Can you paste the data, and an MWE that reproduces the behaviour?

**Comment by bscully27** [comment]
this does not complete:

import numpy as np
import entropy_based_binning as ebb

ar = np.random.randint(0, 25, size=(200, 1)).flatten()
%timeit ebb.bin_sequence(ar, nbins=10)


the initial data was:

array([  5.,   0.,   3.,  11.,   3.,  -1.,  -1.,   4.,  -2.,  10.,  -2.,
         3.,   4.,  -1.,   4.,   0.,   6.,   4.,   3.,   9.,  -8.,   0.,
        -1.,   4.,  -7.,   8.,  10.,  -6.,  -2.,  11.,  -6.,   3.,   2.,
         4., -11.,  -2.,  -5.,   5.,  -5.,   8.,   9.,   6.,   0.,  -4.,
         1.,  -3.,  -9.,  -2.,   2.,  -3.,   1.,   0.,   2.,   8.,  -4.,
         3., -10.,  -2.,   1.,  -7.,  -2.,   4.,  14.,  -2.,   3.,   9.,
        -0.,   7.,  -7.,  -5.,  -3.,   6.,   1.,   5.,   9.,   3.,   0.,
         6.,  14.,  -3.,   8.,   7.,   7.,  -7.,  -8.,  -6.,   6.,  10.,
        -5.,   6.,  -1., -13.,  -1.,   8.,  -5.,   1.,  -6.,  -8.,  -1.,
        14.,   5.,   2.,  -7.,  10.,  -5.,  -2.,   4.,   9.,  -1.,  -0.,
        -9.,  12.,   7.,  -1.,  -0.,  14.,  -6.,  -5.,   2.,  -7.,  -4.,
         5.,   2.,  -6.,  -9.,  12.,   8.,  12.,  -1.,  -5.,  13.,  -1.,
         3.,  -4.,   0.,  -6.,   7.,  -5.,   5.,   0.,  13.,   8.,  -5.,
       -11.,  -5.,  -6.,  -7.,  -5.,   5.,  -1.,   6.,  -0.,  -3.,   2.,
        10.,  -8.,  -2.,  -7.,  10.,   1.,  -6.,  -1.,  -6.,   0.,   6.,
        10.,   4.,  -5.,  -6.,  -0.,   3.,  12.,  14.,   1.,   1.,   1.,
        -8.,  -4.,  -5.,  -1.,  -9.,   9.,   1.,  -4.,  -2.,  -6.,   1.,
        -6.,  -4., -10.,   5.,   4.,  -8.,   6.,  -3.,   5.,  -5.,   1.,
        12.,   3.])

**Comment by paulbrodersen** [comment]
On my machine, this calculation completes and returns: 
```
1min 24s ± 4.25 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by bscully27** [comment]
two issues in my opinion:
1) why it doesnt run on my py2.7 windows machine
2) 200 element array should be binned in milliseconds, not ~84seconds

**Comment by paulbrodersen** [comment]
1) The code should be python 2.7 compatible (because that is the only thing I used when I wrote the module). However, python 2.7 is also officially deprecated, and my time on earth is limited so I don't plan to support it should there actually be some incompatibility. 

2) According to whom? I think you underestimate the complexity of the task. We are dealing with discrete quantities so this is not an optimization problem with a smooth cost function that would allow us to determine a global minimum by gradient descent. Further a recursive, divide-and-conquer approach (e.g. as discussed [here](https://natmeurer.com/a-simple-guide-to-entropy-based-discretization/)) is not guaranteed to converge on the global optimum. That leaves brute-force, i.e. complete enumeration of all possible binnings, which in your case are a whopping 1307505.     

Computing all possible binnings is not so bad, as shown in the line_profiler report below:

```
Total time: 121.441 s
File: /home/paul/.virtualenvs/ebb/lib/python3.6/site-packages/entropy_based_binning/_main.py
Function: bin_sequence at line 7

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     7                                           def bin_sequence(a, nbins):
     8                                               """
     9                                               Find and apply the maximum entropy binning to an integer sequence,
    10                                               given the number of target bins.
    11
    12                                               Arguments:
    13                                               ----------
    14                                               a: (N, ) ndarray
    15                                                   input sequence; must be integer
    16
    17                                               nbins: int
    18                                                   number of bins
    19
    20                                               Returns:
    21                                               --------
    22                                               b: (N, ) ndarray
    23                                                   binned sequence
    24
    25                                               """
    26         1        280.0    280.0      0.0      assert np.all(np.logical_or(_isinteger(a), np.isnan(a))), "Input has to be integer or integer-like!"
    27
    28         1        343.0    343.0      0.0      amin, amax = np.int(np.nanmin(a)), np.int(np.nanmax(a))
    29         1          4.0      4.0      0.0      best_h = 0.
    30
    31   1307505    7562260.0      5.8      6.2      for binning in _generate_bins(range(amin, amax+1), nbins):
    32   1307504  112728222.0     86.2     92.8          h = _evaluate_binning(a, binning)
    33   1307504    1149511.0      0.9      0.9          if h > best_h:
    34       118        117.0      1.0      0.0              best_h = h
    35       118        189.0      1.6      0.0              best_binning = binning
    36
    37         1         52.0     52.0      0.0      return _apply_binning(a, best_binning)
```

So most of the time is spent evaluating each binning. 
That function is: 

```python
def _evaluate_binning(a, binning):
    b = _apply_binning(a, binning)
    h = _get_h(b)
    return h
```

Running `line_profiler` on that function (with the above function call) returns:

```
In [5]: %lprun -f ebb._evaluate_binning ebb.bin_sequence(arr, 10)
Timer unit: 1e-06 s

Total time: 115.332 s
File: /home/paul/src/entropy_based_binning/entropy_based_binning/_main.py
Function: _evaluate_binning at line 98

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    98                                           def _evaluate_binning(a, binning):
    99   1307504   74667336.0     57.1     64.7      b = _apply_binning(a, binning)
   100   1307504   39992013.0     30.6     34.7      h = _get_h(b)
   101   1307504     672574.0      0.5      0.6      return h
```

So both, applying the binning and then evaluating the Shannon entropy given the binning are about equally time consuming. 

These two functions are: 

```python
def _apply_binning(a, binning):
    b = np.full_like(a, np.nan, dtype=np.float)
    for ii, some_bin in enumerate(binning):
        for some_number in some_bin:
            b[a==some_number] = ii
    return b.astype(a.dtype)

def _get_h(b):
    counts = np.bincount(b[~np.isnan(b)].astype(np.int))
    pdf = counts.astype(np.float) / np.sum(counts)
    h = -np.sum(np.ma.filled(pdf * np.log2(pdf), fill_value=0))
    return h
```

If you have a suggestion how to speed up either (and really, you would have to speed up both to make a substantial change to the running time), then I am all ears.

**Comment by paulbrodersen** [comment]
Of course, if you can figure out a better approach than brute force (that is nevertheless guaranteed to find the global optimum), then I would also be interested in hearing about it.

**Comment by bscully27** [comment]
The problem may be the packaging...
I was going to start optimizing with numpy and possibly numba decorators but got significantly faster times just loading the functions into memory.

runfile('*\_main.py')
a = np.random.randint(0, 10, size=(200, 1)).flatten()
%timeit bin_sequence(a, nbins=10)

The slowest run took 4.65 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 86.6 µs per loop


Bored at work so I'll take a quick look at optimizing as well.

**Comment by paulbrodersen** [comment]
Your new test example is the degenerate case where there is a single possible binning (there is only one way to map the integers from 0-9 to 10 consecutive, non-empty bins). I would stick to your first example.

**Comment by paulbrodersen** [comment]
Though I am glad to hear the code runs to completion. ;-)

**Comment by paulbrodersen** [comment]
I just pushed 09c85b8, which adds two functions `bin_sequence_approximately` and `bin_array_approximately` (the latter being a convenience wrapper around the former for arrays). These implement a heuristic, namely equal frequency binning using a recursive approach. This approach is fast: 

```
In [5]: %timeit ebb.bin_sequence_approximately(arr, 8)
621 µs ± 6.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [6]: %timeit ebb.bin_sequence(arr, 8)
22.3 s ± 171 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

However, the heuristic is not guaranteed to find the optimal solution, and the number of bins must be a power of two (due to the recursive approach). I did a few tests in the regime of your use case (200 samples in range 0-24 binned into 8 bins), and in all cases, the heuristic recovered the optimal solution. I haven't uploaded it to PyPI, yet, as I haven't tested it extensively,  yet, so you will have to install from source:

```shell
git clone https://github.com/paulbrodersen/entropy_based_binning.git
cd entropy_based_binning
pip install -e . 
```
